import { Injectable } from '@angular/core';
import * as _ from 'lodash';
import { TableSorterPagination } from './modules/nb-table-sorter/table-sorter.component';
import { PaginationService } from './modules/nb-table-sorter/services/pagination.service';

@Injectable({
	providedIn: 'root'
})
export class MockedUsersService {

	items: any[] = [
		{ id: 1, username: 'gabriel', email: 'gabriel.gonzalez@fakecompany.es', name: 'Gabriel González' },
		{ id: 2, username: 'fran', email: 'paco.arias@fakecompany.es', name: 'Paco Arias' },
		{ id: 3, username: 'francis', email: 'paco.romero@fakecompany.es', name: 'Paco Romero' },
		{ id: 4, username: 'miguel', email: 'miguel.alfaro@fakecompany.es', name: 'Miguel Alfaro' },
		{ id: 5, username: 'fernando', email: 'fernando.gordo@fakecompany.es', name: 'Fernando Gordo' },
		{ id: 6, username: 'marta', email: 'marta.blazquez@fakecompany.es', name: 'Marta Blazquez' },
		{ id: 7, username: 'luis', email: 'luis.martinez@fakecompany.es', name: 'Luis Martínez Martínez' },
		{ id: 8, username: 'jaime', email: 'jaime.carrion@fakecompany.es', name: 'Jaime Carrión' },
		{ id: 9, username: 'javi', email: 'miguel.villanueva@fakecompany.es', name: 'Miguel Villanueva' },
		{ id: 10, username: 'jalberto', email: 'juanalberto.martinez@fakecompany.es', name: 'Juan Alberto Martínez' },
		{ id: 11, username: 'guillermo', email: 'guillermo.sanchez@fakecompany.es', name: 'Guillermo Sánchez' },
		{ id: 12, username: 'ecollado', email: 'eduardo.collado@fakecompany.es', name: 'Eduardo Collado' },
		{ id: 13, username: 'ignacio', email: 'ignacio.martinez2@fakecompany.es', name: 'Ignacio Martínez' },
		{ id: 14, username: 'adrian', email: 'adrian.maestro@fakecompany.es', name: 'Adrián Maestro' },
		{ id: 15, username: 'jluis', email: 'juanluis.lopez@fakecompany.com', name: 'Juan Luis Lopez' },
		{ id: 16, username: 'chus', email: 'chus.lamela@fakecompany.es', name: 'Chus Lamela' },
		{ id: 17, username: 'raul', email: 'raul.guinales@fakecompany.es', name: 'Raul Guiñales' },
		{ id: 18, username: 'JCano', email: 'miguel.cano@fakecompany.es', name: 'Miguel Cano' },
		{ id: 19, username: 'ARogero', email: 'roberto.rogero@fakecompany.es', name: 'Roberto Rogero' },
		{ id: 20, username: 'vicent', email: 'vicent.alonso@fakecompany.es', name: 'Vicent Alonso' },
		{ id: 21, username: 'jose', email: 'josepedro.catalan@fakecompany.es', name: 'Jose Pedro Catalán' },
		{ id: 22, username: 'rubiales', email: 'miguel.rubiales@fakecompany.es', name: 'Miguel Rubiales' },
		{ id: 23, username: 'ana', email: 'ana.lozano@fakecompany.es', name: 'Ana Lozano' },
		{ id: 24, username: 'CMorcillo', email: 'ignacio.morcillo@fakecompany.es', name: 'Ignacio Morcillo' },
		{ id: 25, username: 'constantino', email: 'constantino.lopez@fakecompany.es', name: 'Constantino Lopez' },
		{ id: 26, username: 'eva', email: 'eva.valera@fakecompany.es', name: 'Eva Valera' },
		{ id: 27, username: 'alopez', email: 'aniceto.lopez@fakecompany.es', name: 'Aniceto López' },
		{ id: 28, username: 'afernandez', email: 'aurelio.fernandez@fakecompany.es', name: 'Aurelio Fernández' },
		{ id: 29, username: 'enueda', email: 'eloy.nueda@fakecompany.es', name: 'Eloy Nueda' },
		{ id: 30, username: 'rmegias', email: 'ramon.megias@fakecompany.es', name: 'Ramón Megías' },
		{ id: 31, username: 'pedro', email: 'pedro.garcia@fakecompany.es', name: 'Pedro García' },
		{ id: 32, username: 'elisa', email: 'elisa.colom@fakecompany.es', name: 'Elisa Colom' },
		{ id: 33, username: 'david', email: 'david.garcia@fakecompany.es', name: 'David García' },
		{ id: 34, username: 'jsaiz', email: 'miguel.saiz@fakecompany.es', name: 'Miguel Saiz' },
		{ id: 35, username: 'fjimenez', email: 'paco.jimenez@fakecompany.es', name: 'Paco Jimenez' },
		{ id: 36, username: 'emilio', email: 'emilio.andujar@fakecompany.es', name: 'Emilio Andujar' },
		{ id: 37, username: 'IJusticia', email: 'isidro.justicia@fakecompany.es', name: 'Isidro Justicia Sanchez' },
		{ id: 38, username: 'ABenito', email: 'andres.benito@fakecompany.es', name: 'Andrís Benito Fuentes' },
		{ id: 39, username: 'JTorcal', email: 'miguel.torcal@fakecompany.es', name: 'Miguel Torcal Arias' },
		{ id: 40, username: 'APanfalone', email: 'pedro.panfalone@fakecompany.es', name: 'Pedro Panfalone Camacho' },
		{ id: 41, username: 'RDacuna', email: 'raul.dacuna@fakecompany.es', name: 'Raúl Dacuña Cabrera' },
		{ id: 42, username: 'JRamírez', email: 'juanignacio.ramirez@fakecompany.es', name: 'Juan Ignacio Ramírez Abad' },
		{ id: 43, username: 'JMendez', email: 'juanmiguel.mendez@fakecompany.es', name: 'Juan Miguel Míndez Blanco' },
		{ id: 44, username: 'ACividanes', email: 'alexis.cividanes@fakecompany.es', name: 'Alejandro Cividanes Díez' },
		{ id: 45, username: 'NGil', email: 'nestor.gil@fakecompany.es', name: 'Nístor Gil' },
		{ id: 46, username: 'AGil', email: 'alberto.gil@fakecompany.es', name: 'Alberto Gil' },
		{ id: 47, username: 'FValverde', email: 'paco.valverde@fakecompany.es', name: 'Paco Valverde Navas' },
		{ id: 48, username: 'jjimenez', email: 'juan.jimenez@fakecompany.es', name: 'Juan Jimenez' },
		{ id: 49, username: 'pedrol', email: 'pedro.lopez@fakecompany.es', name: 'Pedro Lopez' },
		{ id: 50, username: 'JMaestre', email: 'jorge.maestre@fakecompany.es', name: 'Jorge Maestre' },
		{ id: 51, username: 'JIbanez', email: 'jose.ibanez@fakecompany.es', name: 'Jose Ibañez' },
		{ id: 52, username: 'IRoman', email: 'ivan.roman@fakecompany.es', name: 'Ivan Roman' },
		{ id: 53, username: 'alexisl', email: 'alexis.lopez@fakecompany.es', name: 'Alejandro Lopez' },
		{ id: 54, username: 'JVela', email: 'juanpedro.vela@fakecompany.es', name: 'Juan Pedro' },
		{ id: 55, username: 'DJustel', email: 'david.justel@fakecompany.es', name: 'David Justel' },
		{ id: 56, username: 'conrado', email: 'conrado.pardo@fakecompany.es', name: 'Conrado Pardo' },
		{ id: 57, username: 'fchus', email: 'paco.macia@fakecompany.es', name: 'Paco Chus Macía' },
		{ id: 58, username: 'ASanchez', email: 'aitor.sanchez@fakecompany.es', name: 'Aitor Sanchez' },
		{ id: 59, username: 'samir', email: 'samir.guerrero@fakecompany.es', name: 'Samir Guerrero' },
		{ id: 60, username: 'arisueno', email: 'pedro.risueno@fakecompany.es', name: 'Pedro Risueño' },
		{ id: 61, username: 'OGarcia', email: 'oscar.garate@fakecompany.es', name: 'Oscar Garcia' },
		{ id: 62, username: 'JGarcia', email: 'chus.garcia@fakecompany.es', name: 'Chus Garcia' },
		{ id: 63, username: 'Gregorio', email: 'gregorio.jimenez@fakecompany.es', name: 'Gregorio Jimínez' },
		{ id: 64, username: 'Pedro', email: 'pedro.monteagudo@fakecompany.es', name: 'Pedro Monteagudo' },
		{ id: 65, username: 'RHernandez', email: 'ruben.hernandez@fakecompany.es', name: 'Rubín Hernández' },
		{ id: 66, username: 'JCSaez', email: 'juanignacio.saez@fakecompany.es', name: 'Juan Ignacio Saez' },
		{ id: 67, username: 'AMedrano', email: 'alvaro.medrano@fakecompany.es', name: 'Alvaro Medrano' },
		{ id: 68, username: 'AValero', email: 'roberto.valero@fakecompany.es', name: 'Roberto Valero' },
		{ id: 69, username: 'GHernansanz', email: 'guillermo.hernansanz@fakecompany.es', name: 'Guillermo Hernansanz' },
		{ id: 70, username: 'CRomero', email: 'ignacio.romero@fakecompany.es', name: 'Ignacio Romero' },
		{ id: 71, username: 'JMLacueva', email: 'josemiguel.lacueva@fakecompany.es', name: 'Jose Miguel Lacueva' },
		{ id: 72, username: 'EMMartinez', email: 'evamaria.martinez@fakecompany.es', name: 'Eva María Martinez' },
		{ id: 73, username: 'jnavarro', email: 'juan.navarro@fakecompany.es', name: 'Juan Navarro' },
		{ id: 74, username: 'silvia', email: 'silvia.salas@fakecompany.es', name: 'Silvia Salas' },
		{ id: 75, username: 'ammarques', email: 'angel.marques@fakecompany.es', name: '\u00c1ngel Marques' },
		{ id: 76, username: 'JuanGarcia', email: 'juan.garcia@fakecompany.es', name: 'Juan García' },
		{ id: 77, username: 'PCuesta', email: 'adrian.cuesta@fakecompany.es', name: 'Adrián Cuesta' },
		{ id: 78, username: 'MHerreros', email: 'miguel.herreros@fakecompany.es', name: 'Miguel Herreros' },
		{ id: 79, username: 'albertoperez', email: 'alberto.perez@fakecompany.es', name: 'Alberto Pírez' },
		{ id: 80, username: 'victorGomez', email: 'victor.gomez@fakecompany.es', name: 'Víctor Gómez' },
		{ id: 81, username: 'alexisOrtiz', email: 'alexis.ortiz@fakecompany.es', name: 'Alejandro Ortiz' },
		{ id: 82, username: 'pedroMartinez', email: 'pedro.martinez@fakecompany.es', name: 'Pedro Martinez' },
		{ id: 83, username: 'adrianMartinez', email: 'adrian.martinez@fakecompany.es', name: 'Adrián Martinez' },
		{ id: 84, username: 'cayetano', email: 'cayetano.laborda@fakecompany.es', name: 'Cayetano Laborda' },
		{ id: 85, username: 'JCerdan', email: 'juan.cerdan@fakecompany.es', name: 'Juan Cerdan' },
		{ id: 86, username: 'CSanchez', email: 'ignacio.sanchez@fakecompany.es', name: 'Ignacio Sanchez' },
		{ id: 87, username: 'ACaravaca', email: 'angel.caravaca@fakecompany.es', name: 'Angel Caravaca' },
		{ id: 88, username: 'FCalvo', email: 'paco.calvo@fakecompany.es', name: 'Paco Calvo' },
		{ id: 89, username: 'marcosGarcia', email: 'marcos.garcia@fakecompany.es', name: 'Marcos García' },
		{ id: 90, username: 'JSanchez', email: 'juan.sanchez@fakecompany.es', name: 'Juan Sánchez' },
		{ id: 91, username: 'jmbarcon', email: 'juanmanuel.barcon@fakecompany.es', name: 'Juan Manuel Barcón Lage ' },
		{ id: 92, username: 'mariaLeal', email: 'maria.leal@fakecompany.es', name: 'Maria Leal' },
		{ id: 93, username: 'jheredia', email: 'jose.heredia@fakecompany.es', name: 'Jose Heredia' },
		{ id: 94, username: 'JMGarcia', email: 'josemaria.garcia@fakecompany.es', name: 'Josí María García' },
		{ id: 95, username: 'DEspinosa', email: 'daniel.espinosa@fakecompany.es', name: 'Daniel Espinosa' },
		{ id: 96, username: 'testing', email: 'testing@fakecompany.es', name: 'Cuenta de testing' },
		{ id: 97, username: 'vnavarro', email: 'vanessa.navarro@fakecompany.es', name: 'Vanessa Navarro Coronado' },
		{ id: 98, username: 'abernal', email: 'adrian.bernal@fakecompany.es', name: 'Adrian Bernal' },
		{ id: 99, username: 'hvelasco', email: 'henar.velasco@fakecompany.es', name: 'Henar Velasco' },
		{ id: 100, username: 'MCPeraile', email: 'mcarmen.peraile@fakecompany.es', name: 'Mari Carmen Peraile' },
		{ id: 101, username: 'JCuartero', email: 'josejoaquin.cuartero@fakecompany.es', name: 'Josí Joaquín' },
		{ id: 102, username: 'RTaviro', email: 'berto.taviro@fakecompany.es', name: 'Roberto' },
		{ id: 103, username: 'LlMolina', email: 'llanos.molina@fakecompany.es', name: 'Llanos' },
		{ id: 104, username: 'ROrtega', email: 'ruben.ortega@fakecompany.es', name: 'Rubín Ortega' },
		{ id: 105, username: 'AMartin', email: 'roberto.martinalbo@fakecompany.es', name: 'Roberto Martín-Albo Martínez' },
		{ id: 106, username: 'JMLopez', email: 'josemanuel.lopez@fakecompany.es', name: 'Jose Manuel Lopez' },
		{ id: 107, username: 'JLMunoz', email: 'joseluis.munoz@fakecompany.es', name: 'Jose Luis Muñoz' },
		{ id: 108, username: 'GGomez', email: 'gabriel.gomez@fakecompany.es', name: 'Gabriel Gómez' },
		{ id: 109, username: 'JLMQuiros', email: 'joseluis.munozquiros@fakecompany.es', name: 'Jose Luis Muñoz Quiros' },
		{ id: 110, username: 'JAlbarran', email: 'jessy.albarran@fakecompany.es', name: 'Jessy Wilben Gabriel' },
		{ id: 111, username: 'MGarrido', email: 'mar.garrido@fakecompany.es', name: 'Marina Garrido' },
		{ id: 112, username: 'JPortillo ', email: 'jose.portillo@fakecompany.es', name: 'Jose Portillo' },
		{ id: 113, username: 'agustin.rosell', email: 'agustin.rosell@fakecompany.es', name: 'Agustín Rosell' },
		{ id: 114, username: 'raul.stan', email: 'raul.stan@fakecompany.es', name: 'Raúl Andrei Stan' },
		{ id: 115, username: 'paco.coronado', email: 'paco.coronado@fakecompany.es', name: 'Paco Manuel Coronado Bonillo' },
		{ id: 116, username: 'miguel.riaza', email: 'miguel.riaza@fakecompany.es', name: 'Miguel Riaza' }
	];

	constructor(
		private _pagination: PaginationService
	) {

	}

	get(params: any): TableSorterPagination {
		return this._pagination.generate(this.items, params);
	}
}
