import { Injectable} from '@angular/core';
import * as _ from 'lodash';
import { TableSorterPagination} from './modules/nb-table-sorter/table-sorter.component';
import { PaginationService } from './modules/nb-table-sorter/services/pagination.service';

@Injectable({
	providedIn: 'root'
})
export class MockedUsersService {

	items: any[] = [
		{ 'id': 1, 'username': 'gabriel', 'email': 'gabriel.gonzalez@fakecompany.es', 'name': 'Gabriel González'},
		{ 'id': 6, 'username': 'fran', 'email': 'francisco.arias@fakecompany.es', 'name': 'Francisco Arias'},
		{ 'id': 8, 'username': 'francis', 'email': 'francisco.romero@fakecompany.es', 'name': 'Francisco Romero'},
		{ 'id': 9, 'username': 'javier', 'email': 'javier.alfaro@fakecompany.es', 'name': 'Javier Alfaro'},
		{ 'id': 10, 'username': 'fernando', 'email': 'fernando.delgado@fakecompany.es', 'name': 'Fernando Delgado'},
		{ 'id': 11, 'username': 'marta', 'email': 'marta.blazquez@fakecompany.es', 'name': 'Marta Blazquez'},
		{ 'id': 12, 'username': 'superadmin', 'email': 'fernando.delgado@fakecompany.es', 'name': 'Fernándo Delgado'},
		{ 'id': 17, 'username': 'luis.arnelio', 'email': 'luis.arnelo@fakecompany.es', 'name': 'Luis Arnelio Martínez'},
		{ 'id': 18, 'username': 'jaime', 'email': 'jaime.carrion@fakecompany.es', 'name': 'Jaime Carrión'},
		{ 'id': 23, 'username': 'javi', 'email': 'javier.villanueva@fakecompany.es', 'name': 'Javier Villanueva'},
		{ 'id': 24, 'username': 'jalberto', 'email': 'juanalberto.martinez@fakecompany.es', 'name': 'Juan Alberto Martínez'},
		{ 'id': 25, 'username': 'guillermo', 'email': 'guillermo.sanchez@fakecompany.es', 'name': 'Guillermo Sánchez'},
		{ 'id': 27, 'username': 'ecollado', 'email': 'eduardo.collado@fakecompany.es', 'name': 'Eduardo Collado'},
		{ 'id': 28, 'username': 'carlos', 'email': 'carlos.martinez2@fakecompany.es', 'name': 'Carlos Martínez'},
		{ 'id': 29, 'username': 'conchi', 'email': 'conchi.aparicio@fakecompany.es', 'name': 'Conchi Aparicio'},
		{ 'id': 30, 'username': 'pablo', 'email': 'pablo.maestro@fakecompany.es', 'name': 'Pablo Maestro'},
		{ 'id': 31, 'username': 'jluis', 'email': 'juanluis.lopez@tudespensa.com', 'name': 'Juan Luis Lopez'},
		{ 'id': 35, 'username': 'jesus', 'email': 'jesus.lamela@fakecompany.es', 'name': 'Jesús Lamela'},
		{ 'id': 36, 'username': 'raul', 'email': 'raul.guinales@fakecompany.es', 'name': 'Raul Guiñales'},
		{ 'id': 38, 'username': 'JCano', 'email': 'javier.cano@fakecompany.es', 'name': 'Javier Cano'},
		{ 'id': 39, 'username': 'ARogero', 'email': 'alfonso.rogero@fakecompany.es', 'name': 'Alfonso Rogero'},
		{ 'id': 40, 'username': 'vicent', 'email': 'vicent.alonso@fakecompany.es', 'name': 'Vicent Alonso'},
		{ 'id': 42, 'username': 'jose', 'email': 'joseantonio.catalan@fakecompany.es', 'name': 'Jose Antonio Catalán'},
		{ 'id': 43, 'username': 'rubiales', 'email': 'javier.rubiales@fakecompany.es', 'name': 'Javier Rubiales'},
		{ 'id': 45, 'username': 'ana', 'email': 'ana.lozano@fakecompany.es', 'name': 'Ana Lozano'},
		{ 'id': 46, 'username': 'CMorcillo', 'email': 'carlos.morcillo@fakecompany.es', 'name': 'Carlos Morcillo'},
		{ 'id': 48, 'username': 'constantino', 'email': 'constantino.lopez@fakecompany.es', 'name': 'Constantino Lopez'},
		{ 'id': 49, 'username': 'eva', 'email': 'eva.valera@fakecompany.es', 'name': 'Eva Valera'},
		{ 'id': 50, 'username': 'alopez', 'email': 'aniceto.lopez@fakecompany.es', 'name': 'Aniceto López'},
		{ 'id': 51, 'username': 'afernandez', 'email': 'aurelio.fernandez@fakecompany.es', 'name': 'Aurelio Fernández'},
		{ 'id': 52, 'username': 'enueda', 'email': 'eloy.nueda@fakecompany.es', 'name': 'Eloy Nueda'},
		{ 'id': 53, 'username': 'rmegias', 'email': 'ramon.megias@fakecompany.es', 'name': 'Ramón Megías'},
		{ 'id': 54, 'username': 'antonio', 'email': 'antonio.garcia@fakecompany.es', 'name': 'Antonio García'},
		{ 'id': 55, 'username': 'elisa', 'email': 'elisa.colom@fakecompany.es', 'name': 'Elisa Colom'},
		{ 'id': 56, 'username': 'david', 'email': 'david.garcia@fakecompany.es', 'name': 'David García'},
		{ 'id': 57, 'username': 'jsaiz', 'email': 'javier.saiz@fakecompany.es', 'name': 'Javier Saiz'},
		{ 'id': 58, 'username': 'fjimenez', 'email': 'francisco.jimenez@fakecompany.es', 'name': 'Francisco Jimenez'},
		{ 'id': 59, 'username': 'emilio', 'email': 'emilio.andujar@fakecompany.es', 'name': 'Emilio Andujar'},
		{ 'id': 60, 'username': 'IJusticia', 'email': 'isidro.justicia@fakecompany.es', 'name': 'Isidro Justicia Sanchez'},
		{ 'id': 61, 'username': 'ABenito', 'email': 'andres.benito@fakecompany.es', 'name': 'Andrís Benito Fuentes'},
		{ 'id': 62, 'username': 'JTorcal', 'email': 'javier.torcal@fakecompany.es', 'name': 'Javier Torcal Arias'},
		{ 'id': 63, 'username': 'APanfalone', 'email': 'antonio.panfalone@fakecompany.es', 'name': 'Antonio Panfalone Camacho'},
		{ 'id': 64, 'username': 'RDacuna', 'email': 'raul.dacuna@fakecompany.es', 'name': 'Raúl Dacuña Cabrera'},
		{ 'id': 65, 'username': 'JRamírez', 'email': 'juancarlos.ramirez@fakecompany.es', 'name': 'Juan Carlos Ramírez Abad'},
		{ 'id': 66, 'username': 'JMendez', 'email': 'juanmiguel.mendez@fakecompany.es', 'name': 'Juan Miguel Míndez Blanco'},
		{ 'id': 67, 'username': 'YRisso', 'email': 'yahaira.risso@fakecompany.es', 'name': 'Yahaira Risso Espinoza'},
		{ 'id': 68, 'username': 'ACividanes', 'email': 'alejandro.cividanes@fakecompany.es', 'name': 'Alejandro Cividanes Díez'},
		{ 'id': 69, 'username': 'NGil', 'email': 'nestor.gil@fakecompany.es', 'name': 'Nístor Gil'},
		{ 'id': 70, 'username': 'AGil', 'email': 'alberto.gil@fakecompany.es', 'name': 'Alberto Gil'},
		{ 'id': 71, 'username': 'FValverde', 'email': 'francisco.valverde@fakecompany.es', 'name': 'Francisco Valverde Navas'},
		{ 'id': 72, 'username': 'HPascual', 'email': 'helena.pascual@fakecompany.es', 'name': 'Helena Pascual'},
		{ 'id': 73, 'username': 'jjimenez', 'email': 'juan.jimenez@fakecompany.es', 'name': 'Juan Jimenez'},
		{ 'id': 74, 'username': 'antoniol', 'email': 'antonio.lopez@fakecompany.es', 'name': 'Antonio Lopez'},
		{ 'id': 75, 'username': 'prueba', 'email': 'vicent.alonso@fakecompany.es', 'name': 'Netberry Test'},
		{ 'id': 76, 'username': 'prueba2', 'email': 'vicent.alonso@fakecompany.es', 'name': 'Prueba '},
		{ 'id': 77, 'username': 'JMaestre', 'email': 'jorge.maestre@fakecompany.es', 'name': 'Jorge Maestre'},
		{ 'id': 78, 'username': 'JIbanez', 'email': 'jose.ibanez@fakecompany.es', 'name': 'Jose Ibañez'},
		{ 'id': 79, 'username': 'IRoman', 'email': 'ivan.roman@fakecompany.es', 'name': 'Ivan Roman'},
		{ 'id': 80, 'username': 'alejandrol', 'email': 'alejandro.lopez@fakecompany.es', 'name': 'Alejandro Lopez'},
		{ 'id': 81, 'username': 'JVela', 'email': 'juanantonio.vela@fakecompany.es', 'name': 'Juan Antonio'},
		{ 'id': 82, 'username': 'DJustel', 'email': 'david.justel@fakecompany.es', 'name': 'David Justel'},
		{ 'id': 83, 'username': 'conrado', 'email': 'conrado.pardo@fakecompany.es', 'name': 'Conrado Pardo'},
		{ 'id': 84, 'username': 'fjesus', 'email': 'francisco.macia@fakecompany.es', 'name': 'Francisco Jesús Macía'},
		{ 'id': 85, 'username': 'ASanchez', 'email': 'aitor.sanchez@fakecompany.es', 'name': 'Aitor Sanchez'},
		{ 'id': 86, 'username': 'samir', 'email': 'samir.guerrero@fakecompany.es', 'name': 'Samir Guerrero'},
		{ 'id': 87, 'username': 'arisueno', 'email': 'antonio.risueno@fakecompany.es', 'name': 'Antonio Risueño'},
		{ 'id': 88, 'username': 'OGarcia', 'email': 'oscar.garate@fakecompany.es', 'name': 'Oscar Garcia'},
		{ 'id': 89, 'username': 'JGarcia', 'email': 'jesus.garcia@fakecompany.es', 'name': 'Jesús Garcia'},
		{ 'id': 90, 'username': 'Gregorio', 'email': 'gregorio.jimenez@fakecompany.es', 'name': 'Gregorio Jimínez'},
		{ 'id': 91, 'username': 'Pedro', 'email': 'pedro.monteagudo@fakecompany.es', 'name': 'Pedro Monteagudo'},
		{ 'id': 92, 'username': 'RHernandez', 'email': 'ruben.hernandez@fakecompany.es', 'name': 'Rubín Hernández'},
		{ 'id': 93, 'username': 'JCSaez', 'email': 'juancarlos.saez@fakecompany.es', 'name': 'Juan Carlos Saez'},
		{ 'id': 94, 'username': 'AMedrano', 'email': 'alvaro.medrano@fakecompany.es', 'name': 'Alvaro Medrano'},
		{ 'id': 95, 'username': 'AValero', 'email': 'alfonso.valero@fakecompany.es', 'name': 'Alfonso Valero'},
		{ 'id': 96, 'username': 'GHernansanz', 'email': 'guillermo.hernansanz@fakecompany.es', 'name': 'Guillermo Hernansanz'},
		{ 'id': 97, 'username': 'CRomero', 'email': 'carlos.romero@fakecompany.es', 'name': 'Carlos Romero'},
		{ 'id': 98, 'username': 'JMLacueva', 'email': 'josemiguel.lacueva@fakecompany.es', 'name': 'Jose Miguel Lacueva'},
		{ 'id': 99, 'username': 'EMMartinez', 'email': 'evamaria.martinez@fakecompany.es', 'name': 'Eva María Martinez'},
		{ 'id': 100, 'username': 'jnavarro', 'email': 'juan.navarro@fakecompany.es', 'name': 'Juan Navarro'},
		{ 'id': 101, 'username': 'silvia', 'email': 'silvia.salas@fakecompany.es', 'name': 'Silvia Salas'},
		{ 'id': 102, 'username': 'ammarques', 'email': 'angel.marques@fakecompany.es', 'name': '\u00c1ngel Marques'},
		{ 'id': 103, 'username': 'JuanGarcia', 'email': 'juan.garcia@fakecompany.es', 'name': 'Juan García'},
		{ 'id': 105, 'username': 'PCuesta', 'email': 'pablo.cuesta@fakecompany.es', 'name': 'Pablo Cuesta'},
		{ 'id': 106, 'username': 'MHerreros', 'email': 'miguel.herreros@fakecompany.es', 'name': 'Miguel Herreros'},
		{ 'id': 107, 'username': 'albertoperez', 'email': 'alberto.perez@fakecompany.es', 'name': 'Alberto Pírez'},
		{ 'id': 108, 'username': 'victorGomez', 'email': 'victor.gomez@fakecompany.es', 'name': 'Víctor Gómez'},
		{ 'id': 109, 'username': 'alejandroOrtiz', 'email': 'alejandro.ortiz@fakecompany.es', 'name': 'Alejandro Ortiz'},
		{ 'id': 110, 'username': 'antonioMartinez', 'email': 'antonio.martinez@fakecompany.es', 'name': 'Antonio Martinez'},
		{ 'id': 111, 'username': 'pabloMartinez', 'email': 'pablo.martinez@fakecompany.es', 'name': 'Pablo Martinez'},
		{ 'id': 112, 'username': 'yohanLaborda', 'email': 'yohan.laborda@fakecompany.es', 'name': 'Yohan Laborda'},
		{ 'id': 113, 'username': 'JCerdan', 'email': 'juan.cerdan@fakecompany.es', 'name': 'Juan Cerdan'},
		{ 'id': 114, 'username': 'CSanchez', 'email': 'carlos.sanchez@fakecompany.es', 'name': 'Carlos Sanchez'},
		{ 'id': 115, 'username': 'ACaravaca', 'email': 'angel.caravaca@fakecompany.es', 'name': 'Angel Caravaca'},
		{ 'id': 116, 'username': 'FCalvo', 'email': 'francisco.calvo@fakecompany.es', 'name': 'Francisco Calvo'},
		{ 'id': 117, 'username': 'marcosGarcia', 'email': 'marcos.garcia@fakecompany.es', 'name': 'Marcos García'},
		{ 'id': 118, 'username': 'JSanchez', 'email': 'juan.sanchez@fakecompany.es', 'name': 'Juan Sánchez'},
		{ 'id': 119, 'username': 'jmbarcon', 'email': 'juanmanuel.barcon@fakecompany.es', 'name': 'Juan Manuel Barcón Lage '},
		{ 'id': 121, 'username': 'mariaLeal', 'email': 'maria.leal@fakecompany.es', 'name': 'Maria Leal'},
		{ 'id': 122, 'username': 'jheredia', 'email': 'jose.heredia@fakecompany.es', 'name': 'Jose Heredia'},
		{ 'id': 123, 'username': 'JMGarcia', 'email': 'josemaria.garcia@fakecompany.es', 'name': 'Josí María García'},
		{ 'id': 124, 'username': 'DEspinosa', 'email': 'daniel.espinosa@fakecompany.es', 'name': 'Daniel Espinosa'},
		{ 'id': 125, 'username': 'testing', 'email': 'testing@fakecompany.es', 'name': 'Cuenta de testing'},
		{ 'id': 126, 'username': 'vnavarro', 'email': 'vanessa.navarro@fakecompany.es', 'name': 'Vanessa Navarro Coronado'},
		{ 'id': 129, 'username': 'abernal', 'email': 'adrian.bernal@fakecompany.es', 'name': 'Adrian Bernal'},
		{ 'id': 131, 'username': 'hvelasco', 'email': 'henar.velasco@fakecompany.es', 'name': 'Henar Velasco'},
		{ 'id': 132, 'username': 'MCPeraile', 'email': 'mcarmen.peraile@fakecompany.es', 'name': 'Mari Carmen Peraile'},
		{ 'id': 133, 'username': 'JCuartero', 'email': 'josejoaquin.cuartero@fakecompany.es', 'name': 'Josí Joaquín'},
		{ 'id': 134, 'username': 'RTaviro', 'email': 'roberto.taviro@fakecompany.es', 'name': 'Roberto'},
		{ 'id': 135, 'username': 'LlMolina', 'email': 'llanos.molina@fakecompany.es', 'name': 'Llanos'},
		{ 'id': 136, 'username': 'ROrtega', 'email': 'ruben.ortega@fakecompany.es', 'name': 'Rubín Ortega'},
		{ 'id': 137, 'username': 'AMartin', 'email': 'alfonso.martinalbo@fakecompany.es', 'name': 'Alfonso Martín-Albo Martínez'},
		{ 'id': 142, 'username': 'JMLopez', 'email': 'josemanuel.lopez@fakecompany.es', 'name': 'Jose Manuel Lopez'},
		{ 'id': 143, 'username': 'JLMunoz', 'email': 'joseluis.munoz@fakecompany.es', 'name': 'Jose Luis Muñoz'},
		{ 'id': 144, 'username': 'GGomez', 'email': 'gabriel.gomez@fakecompany.es', 'name': 'Gabriel Gómez'},
		{ 'id': 145, 'username': 'JLMQuiros', 'email': 'joseluis.munozquiros@fakecompany.es', 'name': 'Jose Luis Muñoz Quiros'},
		{ 'id': 147, 'username': 'JAlbarran', 'email': 'jessy.albarran@fakecompany.es', 'name': 'Jessy Wilben Gabriel'},
		{ 'id': 148, 'username': 'MGarrido', 'email': 'marina.garrido@fakecompany.es', 'name': 'Marina Garrido'},
		{ 'id': 149, 'username': 'JPortillo ', 'email': 'jose.portillo@fakecompany.es', 'name': 'Jose Portillo'},
		{ 'id': 150, 'username': 'agustin.rosell', 'email': 'agustin.rosell@fakecompany.es', 'name': 'Agustín Rosell'},
		{ 'id': 151, 'username': 'raul.stan', 'email': 'raul.stan@fakecompany.es', 'name': 'Raúl Andrei Stan'},
		{ 'id': 152, 'username': 'francisco.coronado', 'email': 'francisco.coronado@fakecompany.es', 'name': 'Francisco Manuel Coronado Bonillo'},
		{ 'id': 153, 'username': 'miguel.riaza', 'email': 'miguel.riaza@fakecompany.es', 'name': 'Miguel Riaza'},
		{ 'id': 154, 'username': 'MMCabanero', 'email': 'mariadelmar.cabanero@fakecompany.es', 'name': 'María del Mar Cabañero'},
		{ 'id': 155, 'username': 'hugo', 'email': 'hugo.ferri@fakecompany.es', 'name': 'Hugo Ferri'}
	];
	constructor(
		private _pagination: PaginationService
	) {

	}

	get(params: any): PaginationService {
		return this._pagination.generate(this.items.concat(), params);
	}
}
